### PR TITLE
Modify host format

### PR DESCRIPTION
**Pull request by antct**
Hi~
I found that there may be an issue with the format of the `dict host_status` key.
If we have two ssh servers like 10.123.123.123:9001 and 10.123.123.123:9002, only using the hostname(10.123.123.123) as the key may cause some conflicts, and the web can only show one server.
Thus, I make a PR of using hostname-port as the dictionary key.
Thanks!

### CODE REVIEW

**Comment by wookayin** [comment]
Thanks for the update. But it seems one may not want to have `port` displayed; especially when all servers are using the standard SSH (22) port. Would you want to make it optional?

**Comment by antct** [comment]
Yes, make it optional is a better choice.
I rewrite the line 122:
```python
return (pr.hostname, 22 if pr.port is None else pr.port)
```

**Review by wookayin — CHANGES_REQUESTED** [review]
No, you should not hardcode 22. It is possible that one uses default SSH port other than 22. My suggestion is: if you have specified another port (e.g. `port != None`), display it like `HOSTNAME:PORT`, but if not (i.e. `port is None`), the port information should not appear in the host string.

**Comment by antct** [comment]
Hi, I rewrite the code to meet your request, and I also add the optional parameter `username`.
username@hostname:port
hostname:port
hostname
Above formats are all ok now.

**Pull request closed without merging**
